const UserActionTypes = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",

  CREATE_ACCOUNT_START: "CREATE_ACCOUNT_START",
  CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
  CREATE_ACCOUNT_FAILURE: "CREATE_ACCOUNT_FAILURE",

  SELECT_CATEGORIES_START: "SELECT_CATEGORIES_START",
  SELECT_CATEGORIES_SUCCESS: "SELECT_CATEGORIES_SUCCESS",
  SELECT_CATEGORIES_FAILURE: "SELECT_CATEGORIES_FAILURE",

  FAVORITE_NEWS: "FAVORITE_NEWS",
  UNFAVORITE_NEWS: "UNFAVORITE_NEWS",

  ADD_READING_TIME_START: "ADD_READING_TIME_START",
  ADD_READING_TIME_SUCCESS: "ADD_READING_TIME_SUCCESS",
  ADD_READING_TIME_FAILURE: "ADD_READING_TIME_FAILURE",
};

export default UserActionTypes;
