export const NewsActionTypes = {
  GET_NEWS_WITH_CATEGORY_START: "GET_NEWS_WITH_CATEGORY_START",
  GET_NEWS_WITH_CATEGORY_SUCCESS: "GET_NEWS_WITH_CATEGORY_SUCCESS",
  GET_NEWS_WITH_CATEGORY_FAILURE: "GET_NEWS_WITH_CATEGORY_FAILURE",

  GET_NEWS_BY_CATEGORY_START: "GET_NEWS_BY_CATEGORY_START",
  GET_NEWS_BY_CATEGORY_SUCCESS: "GET_NEWS_BY_CATEGORY_SUCCESS",
  GET_NEWS_BY_CATEGORY_FAILURE: "GET_NEWS_BY_CATEGORY_FAILURE",

  GET_NEWS_START: "GET_NEWS_START",
  GET_NEWS_SUCCESS: "GET_NEWS_SUCCESS",
  GET_NEWS_FAILURE: "GET_NEWS_FAILURE",

  GET_CATEGORIES_START: "GET_CATEGORIES_START",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

  GET_NEWS_PAGINATED_START: "GET_NEWS_PAGINATED_START",
  GET_NEWS_PAGINATED_SUCCESS: "GET_NEWS_PAGINATED_SUCCESS",
  GET_NEWS_PAGINATED_FAILURE: "GET_NEWS_PAGINATED_FAILURE",

  CLEAR_STATE: "CLEAR_STATE",
  CLEAR_NEWS_LIST_STATE: "CLEAR_NEWS_LIST_STATE",
  CLEAR_NEWS_LIST_CATEGORIES_STATE: "CLEAR_NEWS_LIST_CATEGORIES_STATE",
};
